
import React from 'react';
import { AnalysisReport, ExecutionResult } from '../types';
import { CheckCircleIcon } from './icons/CheckCircleIcon';
import { XCircleIcon } from './icons/XCircleIcon';
import { LinkIcon } from './icons/LinkIcon';

// A type guard to check if the report is a full AnalysisReport
function isAnalysisReport(report: any): report is AnalysisReport {
  return report && report.summary && typeof report.summary.passRate !== 'undefined';
}

const ResultCard: React.FC<{ result: ExecutionResult }> = ({ result }) => (
    <div className="bg-gray-800 p-4 rounded-lg border border-gray-700">
        <div className="flex items-center justify-between">
            <p className="text-gray-300 flex-1 pr-4">{result.testCaseDescription}</p>
            <div className="flex items-center gap-2">
                {result.verdict === 'PASSED' 
                    ? <><CheckCircleIcon className="w-6 h-6 text-green-400" /> <span className="text-green-400 font-semibold">PASSED</span></>
                    : <><XCircleIcon className="w-6 h-6 text-red-400" /> <span className="text-red-400 font-semibold">FAILED</span></>
                }
            </div>
        </div>
        <div className="text-xs text-gray-500 mt-2">Duration: {(result.duration / 1000).toFixed(2)}s</div>
        {result.artifacts.screenshotUrl && (
            <div className="mt-3">
                <a href={result.artifacts.screenshotUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-sm text-sky-400 hover:text-sky-300">
                    <LinkIcon className="w-4 h-4" /> View Artifacts
                </a>
            </div>
        )}
    </div>
);

export const ReportView: React.FC<{ report: AnalysisReport | { summary: string; results: ExecutionResult[] } }> = ({ report }) => {
  if (!isAnalysisReport(report)) {
    // This is for the intermediate view after execution but before analysis
    return (
        <div className="animate-fade-in">
            <h3 className="text-2xl font-bold text-sky-400 mb-4">Execution Results</h3>
            <div className="space-y-3">
                {report.results.map(result => <ResultCard key={result.testCaseId} result={result} />)}
            </div>
        </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      <div>
        <h3 className="text-3xl font-bold text-sky-400">📊 Analysis Report</h3>
        <p className="text-gray-400 mt-1">Generated by AnalyzerAgent</p>
      </div>

      {/* Summary */}
      <div className="bg-gray-800/50 rounded-lg p-6 border border-gray-700">
        <h4 className="text-xl font-semibold text-gray-200 mb-4">Executive Summary</h4>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-center">
            <div><p className="text-2xl font-bold text-sky-400">{report.summary.totalTests}</p><p className="text-sm text-gray-400">Total Tests</p></div>
            <div><p className="text-2xl font-bold text-green-400">{report.summary.passed}</p><p className="text-sm text-gray-400">Passed</p></div>
            <div><p className="text-2xl font-bold text-red-400">{report.summary.failed}</p><p className="text-sm text-gray-400">Failed</p></div>
            <div><p className="text-2xl font-bold text-yellow-400">{report.summary.passRate}</p><p className="text-sm text-gray-400">Pass Rate</p></div>
        </div>
      </div>
      
      {/* Suggestions for Planner */}
      <div className="bg-gray-800/50 rounded-lg p-6 border border-gray-700">
          <h4 className="text-xl font-semibold text-gray-200 mb-3">💡 Suggestions for PlannerAgent</h4>
          <ul className="list-disc list-inside space-y-2 text-gray-300">
              {report.suggestionsForPlanner.map((suggestion, i) => <li key={i}>{suggestion}</li>)}
          </ul>
      </div>

      {/* Detailed Results */}
      <div>
          <h4 className="text-xl font-semibold text-gray-200 mb-3">Detailed Test Results</h4>
          <div className="space-y-3">
              {report.results.map(result => <ResultCard key={result.testCaseId} result={result} />)}
          </div>
      </div>
    </div>
  );
};
